name: update readme
description: "update the notebook index in readme"

inputs:
  GITHUB_TOKEN:
    description: "secrets.GITHUB_TOKEN"
    required: true
  actor:
    description: "github.actor"
    required: true
  branch:
    description: "Target branch name to push the index"
    required: true
    default: "gh-page"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: update readme index
      run: |
        python update_readme.py
    - name: push to gh-page
      shell: bash
      run: |
        REMOTE=https://${{ inputs.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git config user.email "${{ inputs.actor }}@users.noreply.github.com"
        git config user.name "${{ inputs.actor }}"
        git pull ${REMOTE}
        git checkout ${{ inputs.branch }}
        git add README.md
        git status
        git commit -am "Add new comment"
        git push ${REMOTE} ${{ inputs.branch }}
